### ISSUE TITLE
Handle programmatic cart additions

### ISSUE THREAD

**Issue by mecha** [RebelCodecom/edd-bookings#1]
The plugin should be able to handle programmatic additions of cart items to the cart (namely via the `edd_add_to_cart()` function).

One such example of this scenario is the [Wish Lists](https://github.com/easydigitaldownloads/edd-wish-lists) extension, which allows users to add items to custom-made lists. From there, items can be moved to the cart.

Since there is no way for the plugin to be able to "guess" or 'fallback" to any time, date or duration, the best solution is to inject the session picker into the checkout page and disallow checkout until a session is selected or the item is removed from the cart.

**Comment by pippinsplugins** [comment]
Recurring Payments is another example plugin that the current method won't work with.

**Comment by mecha** [comment]
The fix for this issue is included in [v2.1.3-RC1](https://github.com/RebelCodecom/edd-bookings/releases/tag/v2.1.3-rc1), for anyone willing to test.
