### ISSUE TITLE
Admin Bookings dropdowns are not clickable in FireFox

### ISSUE THREAD

**Issue by cklosowski** [RebelCodecom/edd-bookings#11]
When trying to add or edit a bookings availability list in FireFox, you cannot click on any of the dropdowns to set the dates or times. They are only available via using the keyboard to navigate with the tab and arrow keys.

**Comment by mecha** [comment]
Confirmed bug for the latest version. Thanks for reporting.

**Comment by mecha** [comment]
@cklosowski Fixed! This will be merged and included in the next release.
