### ISSUE TITLE
Calendar doesn't show on [purchase_link]

### ISSUE THREAD

**Issue by pippinsplugins** [RebelCodecom/edd-bookings#13]
When using the [purchase_link] shortcode to display a purchase button, the calendar needs to be displayed. Right now it is not.

**Comment by mecha** [comment]
Confirmed bug. The output is being deliberately limited to single Download pages [here](https://github.com/RebelCodecom/edd-bookings/blob/develop/includes/Renderer/FrontendRenderer.php#L22). We'll include a fix in the next version.

**Comment by mecha** [comment]
@pippinsplugins Fixed! I'll be merging this so it will be included in the next release.

**Comment by pippinsplugins** [comment]
:+1:
