### ISSUE TITLE
Add option to change cart message

### ISSUE THREAD

**Issue by mintplugins** [RebelCodecom/edd-bookings#3]
When purchasing a bookings product, if it ended up in your cart without having a date picked (direct buy URL etc), a message appears that says "Error: The item "Judo Class" in your cart requires a booking session. Kindly choose one."

This type of language may not suit every site out there and customers will want to be able to customize that message. 

**Proposal:**
Add an option to the bookings settings page which allows customers to enter their own error message for the cart so they can direct their customers in their own words.

**Comment by mecha** [comment]
Thanks @mintplugins. We like the suggestion and think it makes sense. In fact we're thinking of adding options for customizing more than just the cart message - but most of the front-end messages.

**Comment by mecha** [comment]
@mintplugins This has been implemented and merged into the `develop` branch.
